---
alertmanager:
  alertmanagerSpec:
    ## AlertmanagerConfigs to be selected to merge and configure Alertmanager with.
    alertmanagerConfigSelector:
      matchExpressions:
        - key: alertconfig
          operator: In
          values:
            - drdk-config

  # https://gist.github.com/milesbxf/e2744fc90e9c41b47aa47925f8ff6512
  templateFiles:
    template_1.tmpl: |-
      {{/* Color of Slack attachment (appears as line next to alert) */}}
      {{ define "slack.dr.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                warning
            {{- else if eq .CommonLabels.severity "critical" -}}
                danger
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        good
        {{- end }}
      {{- end }}

      {/* A helper template */}}
      {{ define "__alert_severity_prefix_title" -}}
        {{ if ne .Status "firing" -}}
        :lgtm:
        {{- else if eq .CommonLabels.severity "critical" -}}
        :fire:
        {{- else if eq .CommonLabels.severity "warning" -}}
        :warning:
        {{- else if eq .CommonLabels.severity "info" -}}
        :information_source:
        {{- else -}}
        :question:
        {{- end }}
      {{- end }}

      {{ define "slack.dr.title" -}}
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ template "__alert_severity_prefix_title" . }} {{ .CommonLabels.alertname }}
      {{- end }}

      {{ define "slack.dr.text" -}}
      {{ range .Alerts }}
          {{- if .Annotations.message }}
              {{ .Annotations.message }}
          {{- end }}
          {{- if .Annotations.description }}
              {{ .Annotations.description }}
          {{- end }}
      {{- end }}
      {{- end }}

      {{ define "slack.dr.silence_link" -}}
          {{ .ExternalURL }}/#/silences/new?filter=%7B
          {{- range .CommonLabels.SortedPairs -}}
            {{- if ne .Name "alertname" -}}
                {{- .Name }}%3D"{{- .Value -}}"%2C%20
            {{- end -}}
          {{- end -}}
          alertname%3D"{{ .CommonLabels.alertname }}"%7D
      {{- end }}
